# MongoDB接続設定
mongodb:
  ip_address: "localhost"  
  port: 27017
  database: "rostmsdb"
  collection: "parameter"

# 初期化するパラメータ設定
initial_parameters:
  - record_name: "SAMPLE_BLACKBOARD_SIPDEMO202508"
    values:
      SENSING_ARRIVAL_FLG : true
      SENSING_LOADED_FLG : false