# Copyright 2023, IRVS Laboratory, Kyushu University, Japan.

# //  Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



# pUll the tiryoh/ros2-desktop-vnc docker image
FROM tiryoh/ros2-desktop-vnc:humble
# LABEL maintainer= "kasahara.yuichiro.res@gmail.com"
RUN . /opt/ros/humble/setup.sh

# set the environment variable OVERLAY_WS to the path of the workspace(ros2_tms_for_construction_ws)
ARG OVERLAY_WS=/opt/
WORKDIR $OVERLAY_WS

# install dependencies
RUN apt update && apt install -y \
    git \
    pip \
    nlohmann-json3-dev \
    python3-pip \
    libzmq3-dev \
    libboost-dev \
    libncurses5-dev \
    libncursesw5-dev \
    wget \
    libgoogle-glog-dev \ 
    ros-humble-behaviortree-cpp-v3 \
    libgtk-3-0 \
    libnotify4 \
    libnss3 \
    libxtst6 \
    xdg-utils \
    libatspi2.0-0 \
    libdrm2 \
    libgbm1 \
    libxcb-dri3-0 \
    libglib2.0-bin \
    gvfs \
    libsecret-1-0 \
    gnome-keyring \
    wget \
    unzip \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

# install pymongo
RUN pip install pymongo

# install mongodb
WORKDIR /home
RUN apt update && apt install -y gnupg curl \
    && curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | \
    gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
    --dearmor
RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list \
    && apt update && apt install -y mongodb-org \
    && echo "mongodb-org hold" | dpkg --set-selections && echo "mongodb-org-database hold" | dpkg --set-selections \
    && echo "mongodb-org-server hold" | dpkg --set-selections && echo "mongodb-mongosh hold" | dpkg --set-selections \
    && echo "mongodb-org-mongos hold" | dpkg --set-selections && echo "mongodb-org-tools hold" | dpkg --set-selections
# データディレクトリの作成
RUN mkdir -p /data/db

# install mongodb compass
RUN wget https://downloads.mongodb.com/compass/mongodb-compass_1.43.0_amd64.deb \
    && dpkg -i mongodb-compass_1.43.0_amd64.deb
# Xvfb のセットアップと dbus & MongoDB serverの起動
RUN chmod +x /usr/bin/mongodb-compass
CMD Xvfb :1 -screen 0 1024x768x16 & \
    service dbus start && \
    export DISPLAY=:1 && \
    xhost +local:root

# setup mongocxx / bsoncxx
WORKDIR /home
RUN wget https://github.com/mongodb/mongo-c-driver/releases/download/1.24.4/mongo-c-driver-1.24.4.tar.gz \
    && tar -xzf mongo-c-driver-1.24.4.tar.gz
WORKDIR /home/mongo-c-driver-1.24.4
RUN mkdir cmake-build
WORKDIR /home/mongo-c-driver-1.24.4/cmake-build
RUN cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF .. -DCMAKE_INSTALL_PREFIX=/usr/local \
    && make install
WORKDIR /home
RUN curl -OL https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.8.1/mongo-cxx-driver-r3.8.1.tar.gz \
    && tar -xzf mongo-cxx-driver-r3.8.1.tar.gz
WORKDIR /home/mongo-cxx-driver-r3.8.1/build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBSONCXX_POLY_USE_BOOST=1 -DMONGOCXX_OVERRIDE_DEFAULT_INSTALL_PREFIX=OFF \
    && cmake --build . \
    && cmake --build . --target install \WORKDIR /home
    RUN wget https://github.com/mongodb/mongo-c-driver/releases/download/1.24.4/mongo-c-driver-1.24.4.tar.gz \
        && tar -xzf mongo-c-driver-1.24.4.tar.gz
    WORKDIR /home/mongo-c-driver-1.24.4
    RUN mkdir cmake-build
    WORKDIR /home/mongo-c-driver-1.24.4/cmake-build
    RUN cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF .. -DCMAKE_INSTALL_PREFIX=/usr/local \
        && make install
    WORKDIR /home
    RUN curl -OL https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.8.1/mongo-cxx-driver-r3.8.1.tar.gz \
        && tar -xzf mongo-cxx-driver-r3.8.1.tar.gz
    WORKDIR /home/mongo-cxx-driver-r3.8.1/build
    RUN cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBSONCXX_POLY_USE_BOOST=1 -DMONGOCXX_OVERRIDE_DEFAULT_INSTALL_PREFIX=OFF \
        && cmake --build . \
        && cmake --build . --target install \
        && export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH \
        && echo 'export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH' >> ~/.bashrc
    WORKDIR /home
    RUN rm -rf mongo-c-driver-1.24.4 mongo-c-driver-1.24.4.tar.gz mongo-cxx-driver-r3.8.1 mongo-cxx-driver-r3.8.1.tar.gz
    && export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH \
    && echo 'export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH' >> ~/.bashrc
WORKDIR /home
RUN rm -rf mongo-c-driver-1.24.4 mongo-c-driver-1.24.4.tar.gz mongo-cxx-driver-r3.8.1 mongo-cxx-driver-r3.8.1.tar.gz