# Goal definition
# Target Pose
trajectory_msgs/JointTrajectory trajectory
geometry_msgs/Pose[] pose_sequence
tms_msg_rp/TmsRpZx200PositionWithAngle[] position_with_angle_sequence

# Constraints for endeffector
# Todo: Fix to use position constraint
# moveit_msgs/Constraints constraints

---

# Result definition
TmsRpErrorCodes error_code

---

# Feedback definition
string state