# Goal definition
# Target Pose
tms_msg_rp/TmsRpExcavatorPositionWithAngle[] position_with_angle_sequence

# Target Joint Values
tms_msg_rp/TmsRpExcavatorJointValues[] joint_values_sequence

# Constraints
moveit_msgs/Constraints constraints

# PlanningScene
moveit_msgs/PlanningScene planning_scene

---

# Result definition
TmsRpErrorCodes error_code
moveit_msgs/RobotTrajectory[] plan

---

# Feedback definition
string state