// ===============================
// primitive_crawlerdump_compute_path_to_pose.cpp
// ===============================

// Copyright 2023, IRVS Laboratory, Kyushu University, Japan.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "tms_ts_primitive/Crawlerdump/primitive_crawlerdump_compute_path_to_pose.hpp"

#include <mongocxx/instance.hpp>

using std::placeholders::_1;
using std::placeholders::_2;

PrimitiveCrawlerDumpComputePathToPose::PrimitiveCrawlerDumpComputePathToPose()
: PrimitiveNodeBase("st_crawlerdump_compute_path_to_pose_node")
, mongo_client_(mongocxx::uri{"mongodb://localhost:27017"})
, mongo_db_(mongo_client_["rostmsdb"])
, mongo_collection_(mongo_db_["parameter"]) 
{
  this->declare_parameter<std::string>("output_model_name", "mst110cr");
  this->declare_parameter<std::string>("output_record_name", "computed_path_autogenerated");

  this->get_parameter("output_model_name", output_model_name_);
  this->get_parameter("output_record_name", output_record_name_);

  RCLCPP_INFO(get_logger(), "output_model_name=%s output_record_name=%s",
              output_model_name_.c_str(), output_record_name_.c_str());
  
    action_server_ = rclcpp_action::create_server<tms_msg_ts::action::LeafNodeBase>(
    this,
    "st_crawlerdump_compute_path_to_pose",
    std::bind(&PrimitiveCrawlerDumpComputePathToPose::handle_goal, this, _1, _2),
    std::bind(&PrimitiveCrawlerDumpComputePathToPose::handle_cancel, this, _1),
    std::bind(&PrimitiveCrawlerDumpComputePathToPose::handle_accepted, this, _1)
  );

  action_client_ = rclcpp_action::create_client<ComputePathToPose>(this, "compute_path_to_pose");

  RCLCPP_INFO(get_logger(), "Mongo ready: db=rostmsdb collection=parameter");
}

rclcpp_action::GoalResponse PrimitiveCrawlerDumpComputePathToPose::handle_goal(
  const rclcpp_action::GoalUUID&,
  std::shared_ptr<const tms_msg_ts::action::LeafNodeBase::Goal> goal)
{
  RCLCPP_INFO(get_logger(), "handle_goal: model=%s record=%s",
              goal->model_name.c_str(), goal->record_name.c_str());

  parameters_ = CustomGetParamFromDB<std::string, double>(goal->model_name, goal->record_name);
  if (parameters_.empty()) {
    RCLCPP_ERROR(get_logger(), "Failed to get parameters from DB (empty result)");
    return rclcpp_action::GoalResponse::REJECT;
  }

  // 2D 運用：無ければ固定値で埋める（エラーにしない）
  if (!has_param_("goal_z"))  { parameters_["goal_z"]  = 0.0; }
  if (!has_param_("goal_qz")) { parameters_["goal_qz"] = 0.0; }

  // 必須（最低限）
  const char* required[] = {"goal_x","goal_y","goal_qx","goal_qy","goal_qw"};
  for (auto k : required) {
    if (!has_param_(k)) {
      RCLCPP_ERROR(get_logger(), "Missing parameter key: %s", k);
      return rclcpp_action::GoalResponse::REJECT;
    }
  }

  return rclcpp_action::GoalResponse::ACCEPT_AND_EXECUTE;
}

rclcpp_action::CancelResponse
PrimitiveCrawlerDumpComputePathToPose::handle_cancel(const std::shared_ptr<GoalHandleLeaf>)
{
  RCLCPP_INFO(get_logger(), "Cancel requested");

  if (client_future_goal_handle_.valid() &&
      client_future_goal_handle_.wait_for(std::chrono::seconds(0)) == std::future_status::ready)
  {
    auto gh = client_future_goal_handle_.get();
    if (gh) {
      action_client_->async_cancel_goal(gh);
    }
  }

  return rclcpp_action::CancelResponse::ACCEPT;
}

void PrimitiveCrawlerDumpComputePathToPose::handle_accepted(const std::shared_ptr<GoalHandleLeaf> goal_handle)
{
  std::thread{std::bind(&PrimitiveCrawlerDumpComputePathToPose::execute, this, goal_handle)}.detach();
}

void PrimitiveCrawlerDumpComputePathToPose::execute(const std::shared_ptr<GoalHandleLeaf> goal_handle)
{
  RCLCPP_INFO(get_logger(), "execute: start");

  // action server 待ち（居なければ abort）
  if (!action_client_->wait_for_action_server(std::chrono::seconds(2))) {
    RCLCPP_ERROR(get_logger(), "Nav2 ComputePathToPose action server not available");
    auto res = std::make_shared<tms_msg_ts::action::LeafNodeBase::Result>();
    res->result = false;
    goal_handle->abort(res);
    return;
  }

  ComputePathToPose::Goal goal_msg;
  geometry_msgs::msg::PoseStamped goal_pose;

  goal_pose.header.stamp = now();
  goal_pose.header.frame_id = "map";

  goal_pose.pose.position.x = get_or_("goal_x", 0.0);
  goal_pose.pose.position.y = get_or_("goal_y", 0.0);
  goal_pose.pose.position.z = get_or_("goal_z", 0.0);

  goal_pose.pose.orientation.x = get_or_("goal_qx", 0.0);
  goal_pose.pose.orientation.y = get_or_("goal_qy", 0.0);
  goal_pose.pose.orientation.z = get_or_("goal_qz", 0.0);
  goal_pose.pose.orientation.w = get_or_("goal_qw", 1.0);

  goal_msg.goal = goal_pose;
  goal_msg.planner_id = "GridBased";
  goal_msg.use_start  = false;

  rclcpp_action::Client<ComputePathToPose>::SendGoalOptions opt;
  opt.goal_response_callback = [this](const auto& gh){ goal_response_callback(gh); };
  opt.feedback_callback      = [this](auto gh, auto fb){ feedback_callback(gh, fb); };
  opt.result_callback        = [this, goal_handle](const auto& r){ result_callback(goal_handle, r); };

  RCLCPP_INFO(get_logger(), "Sending goal: (%.3f, %.3f)",
              goal_pose.pose.position.x, goal_pose.pose.position.y);

  client_future_goal_handle_ = action_client_->async_send_goal(goal_msg, opt);
}

void PrimitiveCrawlerDumpComputePathToPose::goal_response_callback(const GoalHandleCompute::SharedPtr& goal_handle)
{
  if (!goal_handle) {
    RCLCPP_ERROR(get_logger(), "Goal rejected by server");
  } else {
    RCLCPP_INFO(get_logger(), "Goal accepted by server");
  }
}

void PrimitiveCrawlerDumpComputePathToPose::feedback_callback(
  GoalHandleCompute::SharedPtr,
  const std::shared_ptr<const ComputePathToPose::Feedback>)
{
  RCLCPP_INFO(get_logger(), "feedback");
}

void PrimitiveCrawlerDumpComputePathToPose::result_callback(
  const std::shared_ptr<GoalHandleLeaf> goal_handle,
  const GoalHandleCompute::WrappedResult& result)
{
  auto out = std::make_shared<tms_msg_ts::action::LeafNodeBase::Result>();

  if (!goal_handle->is_active()) {
    RCLCPP_WARN(get_logger(), "Goal not active anymore");
    return;
  }

  if (result.code != rclcpp_action::ResultCode::SUCCEEDED) {
    out->result = false;

    if (result.code == rclcpp_action::ResultCode::ABORTED) {
      goal_handle->abort(out);
    } else if (result.code == rclcpp_action::ResultCode::CANCELED) {
      goal_handle->canceled(out);
    } else {
      goal_handle->abort(out);
    }

    RCLCPP_ERROR(get_logger(), "ComputePathToPose failed: code=%d", (int)result.code);
    return;
  }

  if (!result.result) {
    out->result = false;
    goal_handle->abort(out);
    RCLCPP_ERROR(get_logger(), "Result is null despite SUCCEEDED");
    return;
  }

  const auto& path = result.result->path;
  RCLCPP_INFO(get_logger(), "Path received: frame=%s poses=%zu",
              path.header.frame_id.c_str(), path.poses.size());

  // ===== Mongo upsert: 同じ(model_name, record_name)があれば上書き、無ければ新規 =====
// ===== Mongo upsert: (model_name, record_name) が同じなら上書き、無ければ挿入 =====
try {
  using bsoncxx::builder::basic::kvp;
  using bsoncxx::builder::basic::document;
  using bsoncxx::builder::basic::array;

  array x_arr, y_arr, z_arr;
  array qx_arr, qy_arr, qz_arr, qw_arr;

  for (const auto& ps : path.poses) {
    const auto& p = ps.pose;
    x_arr.append(p.position.x);
    y_arr.append(p.position.y);
    z_arr.append(p.position.z);
    qx_arr.append(p.orientation.x);
    qy_arr.append(p.orientation.y);
    qz_arr.append(p.orientation.z);
    qw_arr.append(p.orientation.w);
  }

  const std::string model_name  = output_model_name_;
  const std::string record_name = output_record_name_;

  array model_arr;
  model_arr.append(model_name);

  document filter;
  filter.append(
    kvp("record_name", record_name),
    kvp("model_name",  [&](bsoncxx::builder::basic::sub_document sd){
      sd.append(kvp("$in", [&](bsoncxx::builder::basic::sub_array sa){
        sa.append(model_name);
      }));
    })
  );

  // --- 更新内容：$set で上書き ---
  document set_doc;
  set_doc.append(
    kvp("model_name",  model_arr.extract()),
    kvp("type",        "static"),
    kvp("record_name", record_name),
    kvp("frame_id",    path.header.frame_id),
    kvp("x",           x_arr.extract()),
    kvp("y",           y_arr.extract()),
    kvp("z",           z_arr.extract()),
    kvp("qx",          qx_arr.extract()),
    kvp("qy",          qy_arr.extract()),
    kvp("qz",          qz_arr.extract()),
    kvp("qw",          qw_arr.extract())
  );

  document update;
  update.append(kvp("$set", set_doc.extract()));

  mongocxx::options::update opt;
  opt.upsert(true);  // ← 無ければ insert される

  auto res = mongo_collection_.update_one(filter.view(), update.view(), opt);

  if (res) {
    const auto matched  = res->matched_count();
    const auto modified = res->modified_count();
    const auto upserted = res->upserted_id().has_value();
    RCLCPP_INFO(get_logger(),
      "Mongo upsert done: matched=%ld modified=%ld upserted=%s",
      (long)matched, (long)modified, upserted ? "true" : "false");
  } else {
    RCLCPP_ERROR(get_logger(), "Mongo upsert failed (null result)");
  }

} catch (const std::exception& e) {
  RCLCPP_ERROR(get_logger(), "Mongo upsert exception: %s", e.what());
}


  out->result = true;
  goal_handle->succeed(out);
  RCLCPP_INFO(get_logger(), "Primitive succeeded");
}



int main(int argc, char* argv[])
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<PrimitiveCrawlerDumpComputePathToPose>());
  rclcpp::shutdown();
  return 0;
}