#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tms-ur-speaker','console_scripts','tms_ur_speaker_node'
__requires__ = 'tms-ur-speaker'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tms-ur-speaker', 'console_scripts', 'tms_ur_speaker_node')()
    )
