string type
int32  id
string filename
bool   latest_only
---
bool   result
string msg
string time
string type
string filename
float32 elevation
float32 offset_x
float32 offset_y
sensor_msgs/Image image
---
bool   result
string msg
string time
string type
int32  id
string filename
float32 elevation
float32 offset_x
float32 offset_y
sensor_msgs/Image image